"""add voice provider job table

Revision ID: 1afcfae4fe8d
Revises: 257b8a397491
Create Date: 2026-09-26 07:59:51.377930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1afcfae4fe8d'
down_revision: Union[str, Sequence[str], None] = '257b8a397491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

voice_generation_status = postgresql.ENUM(
    "pending",
    "processing",
    "completed",
    "failed",
    name="voicegenerationstatus",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""

    voice_generation_status.create(
        op.get_bind(),
        checkfirst=True,
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_provider_jobs',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voice_generation_uid', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='voiceproviderjobstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['voice_generation_uid'], ['voice_generations.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_voice_provider_jobs_idempotency_key'), 'voice_provider_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_voice_provider_jobs_provider_job_id'), 'voice_provider_jobs', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_voice_provider_jobs_uid'), 'voice_provider_jobs', ['uid'], unique=False)
    op.create_index(op.f('ix_voice_provider_jobs_voice_generation_uid'), 'voice_provider_jobs', ['voice_generation_uid'], unique=False)
    op.add_column(
            "voice_generations",
            sa.Column(
                "status",
                voice_generation_status,
                nullable=False,
                server_default="pending",
            ),
        )

    op.add_column('voice_generations', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('voice_generations', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('voice_generations', 'audio_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_voice_generation_language_voice'), 'voice_generations', type_='unique')
    op.create_unique_constraint('uq_voice_generation_content_voice', 'voice_generations', ['generation_uid', 'language', 'platform', 'voice'])

    op.alter_column(
        "voice_generations",
        "status",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_voice_generation_content_voice', 'voice_generations', type_='unique')
    op.create_unique_constraint(op.f('uq_voice_generation_language_voice'), 'voice_generations', ['generation_uid', 'language', 'voice', 'platform'], postgresql_nulls_not_distinct=False)
    op.alter_column('voice_generations', 'audio_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('voice_generations', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('voice_generations', 'error_message')
    op.drop_column(
        "voice_generations",
        "status",
    )

    voice_generation_status.drop(
        op.get_bind(),
        checkfirst=True,
    )
    op.drop_index(op.f('ix_voice_provider_jobs_voice_generation_uid'), table_name='voice_provider_jobs')
    op.drop_index(op.f('ix_voice_provider_jobs_uid'), table_name='voice_provider_jobs')
    op.drop_index(op.f('ix_voice_provider_jobs_provider_job_id'), table_name='voice_provider_jobs')
    op.drop_index(op.f('ix_voice_provider_jobs_idempotency_key'), table_name='voice_provider_jobs')
    op.drop_table('voice_provider_jobs')
    # ### end Alembic commands ###
