"""cascade delete otp when user deleted

Revision ID: 1fcef7db84ca
Revises: 6fb3fd8a93d4
Create Date: 2026-09-16 18:45:41.790343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcef7db84ca'
down_revision: Union[str, Sequence[str], None] = '6fb3fd8a93d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('otp_verification_user_uid_fkey'), 'otp_verification', type_='foreignkey')
    op.create_foreign_key(None, 'otp_verification', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otp_verification', type_='foreignkey')
    op.create_foreign_key(op.f('otp_verification_user_uid_fkey'), 'otp_verification', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###
