"""first database migration

Revision ID: 6fb3fd8a93d4
Revises: 
Create Date: 2026-09-16 07:32:19.405221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6fb3fd8a93d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sa.Enum('local', 'google', 'github', name='auth_provider'), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.create_table('otp_verification',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', name='otp_purpose'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_otp_verification_uid'), 'otp_verification', ['uid'], unique=False)
    op.create_index(op.f('ix_otp_verification_user_uid'), 'otp_verification', ['user_uid'], unique=False)
    op.create_table('projects',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('workflow', sa.Enum('social', 'campaign', 'speech', name='project_workflow'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'completed', 'published', 'archived', name='project_status'), nullable=False),
    sa.Column('objective', sa.Enum('awareness', 'engagement', 'education', 'conversion', 'lead_generation', 'promotion', 'sales_conversion', 'retention', 'community_building', 'storytelling', 'inspiration', 'event_promotion', 'fundraising', 'product_launch', name='content_objective'), nullable=False),
    sa.Column('tone', sa.Enum('professional', 'friendly', 'formal', 'conversational', 'persuasive', 'humorous', 'inspirational', 'educational', name='content_tone'), nullable=False),
    sa.Column('audiences', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('platforms', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_document_text', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_count', sa.Integer(), nullable=False),
    sa.Column('length', sa.Enum('short', 'medium', 'long', 'extended', name='content_length'), nullable=True),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_projects_uid'), 'projects', ['uid'], unique=False)
    op.create_index(op.f('ix_projects_user_uid'), 'projects', ['user_uid'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_uid', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_uid'], ['refresh_tokens.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_uid'), 'refresh_tokens', ['uid'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_uid'), 'refresh_tokens', ['user_uid'], unique=False)
    op.create_table('usage_analytics',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('ai_requests', sa.Integer(), nullable=False),
    sa.Column('tts_requests', sa.Integer(), nullable=False),
    sa.Column('image_requests', sa.Integer(), nullable=False),
    sa.Column('video_requests', sa.Integer(), nullable=False),
    sa.Column('pdf_exports', sa.Integer(), nullable=False),
    sa.Column('content_shares', sa.Integer(), nullable=False),
    sa.Column('audio_shares', sa.Integer(), nullable=False),
    sa.Column('storage_used_mb', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_usage_analytics_uid'), 'usage_analytics', ['uid'], unique=False)
    op.create_index(op.f('ix_usage_analytics_user_uid'), 'usage_analytics', ['user_uid'], unique=True)
    op.create_table('user_preferences',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('default_language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_tone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_voice', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('default_workflow', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_preferences_uid'), 'user_preferences', ['uid'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_uid'), 'user_preferences', ['user_uid'], unique=True)
    op.create_table('assets',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('AUDIO', 'IMAGE', 'VIDEO', 'PDF', 'DOCUMENT', 'THUMBNAIL', 'COVER', name='assettype'), nullable=False),
    sa.Column('provider', sa.Enum('CLOUDINARY', 'YARNGPT', 'OPENAI', 'RUNWAY', 'LOCAL', 'USER_UPLOAD', name='assetprovider'), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_assets_project_uid'), 'assets', ['project_uid'], unique=False)
    op.create_index(op.f('ix_assets_uid'), 'assets', ['uid'], unique=False)
    op.create_index(op.f('ix_assets_user_uid'), 'assets', ['user_uid'], unique=False)
    op.create_table('generations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_uid', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='generation_status'), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('memories', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_uid'], ['projects.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_generations_project_uid'), 'generations', ['project_uid'], unique=False)
    op.create_index(op.f('ix_generations_uid'), 'generations', ['uid'], unique=False)
    op.create_table('voice_generations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_uid', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('voice', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cloudinary_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('response_format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['generation_uid'], ['generations.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('generation_uid', 'language', 'voice', 'platform', name='uq_voice_generation_language_voice')
    )
    op.create_index(op.f('ix_voice_generations_generation_uid'), 'voice_generations', ['generation_uid'], unique=False)
    op.create_index(op.f('ix_voice_generations_uid'), 'voice_generations', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_generations_uid'), table_name='voice_generations')
    op.drop_index(op.f('ix_voice_generations_generation_uid'), table_name='voice_generations')
    op.drop_table('voice_generations')
    op.drop_index(op.f('ix_generations_uid'), table_name='generations')
    op.drop_index(op.f('ix_generations_project_uid'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_assets_user_uid'), table_name='assets')
    op.drop_index(op.f('ix_assets_uid'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_uid'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_user_preferences_user_uid'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_uid'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_usage_analytics_user_uid'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_uid'), table_name='usage_analytics')
    op.drop_table('usage_analytics')
    op.drop_index(op.f('ix_refresh_tokens_user_uid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_uid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_uid'), table_name='projects')
    op.drop_index(op.f('ix_projects_uid'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_otp_verification_user_uid'), table_name='otp_verification')
    op.drop_index(op.f('ix_otp_verification_uid'), table_name='otp_verification')
    op.drop_table('otp_verification')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
