"""update asset table

Revision ID: 8a40b0ddd44a
Revises: b53815457325
Create Date: 2026-09-30 14:42:40.534201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a40b0ddd44a'
down_revision: Union[str, Sequence[str], None] = 'b53815457325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'project_uid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'project_uid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
