"""add voice generation and voice provider table

Revision ID: b020eeb7cf96
Revises: 1afcfae4fe8d
Create Date: 2026-09-26 09:22:13.933619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b020eeb7cf96'
down_revision: Union[str, Sequence[str], None] = '1afcfae4fe8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_generations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_uid', sa.Uuid(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('voice', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='voice_generation_status'), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloudinary_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('response_format', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['generation_uid'], ['generations.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('generation_uid', 'language', 'platform', 'voice', name='uq_voice_generation_content_voice')
    )
    op.create_index(op.f('ix_voice_generations_generation_uid'), 'voice_generations', ['generation_uid'], unique=False)
    op.create_index(op.f('ix_voice_generations_uid'), 'voice_generations', ['uid'], unique=False)
    op.create_table('voice_provider_jobs',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voice_generation_uid', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_job_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'queued', 'processing', 'completed', 'failed', name='voice_provider_job_status'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['voice_generation_uid'], ['voice_generations.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_voice_provider_jobs_idempotency_key'), 'voice_provider_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_voice_provider_jobs_provider_job_id'), 'voice_provider_jobs', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_voice_provider_jobs_uid'), 'voice_provider_jobs', ['uid'], unique=False)
    op.create_index(op.f('ix_voice_provider_jobs_voice_generation_uid'), 'voice_provider_jobs', ['voice_generation_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_provider_jobs_voice_generation_uid'), table_name='voice_provider_jobs')
    op.drop_index(op.f('ix_voice_provider_jobs_uid'), table_name='voice_provider_jobs')
    op.drop_index(op.f('ix_voice_provider_jobs_provider_job_id'), table_name='voice_provider_jobs')
    op.drop_index(op.f('ix_voice_provider_jobs_idempotency_key'), table_name='voice_provider_jobs')
    op.drop_table('voice_provider_jobs')
    op.drop_index(op.f('ix_voice_generations_uid'), table_name='voice_generations')
    op.drop_index(op.f('ix_voice_generations_generation_uid'), table_name='voice_generations')
    op.drop_table('voice_generations')
    # ### end Alembic commands ###
