"""add image generation table

Revision ID: b53815457325
Revises: c49c63bb1ed1
Create Date: 2026-09-30 08:01:54.964113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b53815457325'
down_revision: Union[str, Sequence[str], None] = 'c49c63bb1ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_uid', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='image_generation_status'), nullable=False),
    sa.Column('source_language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_variant', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('design_brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloudinary_public_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['generation_uid'], ['generations.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_image_generations_generation_uid'), 'image_generations', ['generation_uid'], unique=False)
    op.create_index(op.f('ix_image_generations_uid'), 'image_generations', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_generations_uid'), table_name='image_generations')
    op.drop_index(op.f('ix_image_generations_generation_uid'), table_name='image_generations')
    op.drop_table('image_generations')
    # ### end Alembic commands ###
