"""add profile url to user table

Revision ID: c49c63bb1ed1
Revises: 73592645ad65
Create Date: 2026-09-28 22:29:13.529479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c49c63bb1ed1'
down_revision: Union[str, Sequence[str], None] = '73592645ad65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_picture_public_id')
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
